#!/usr/bin/env zsh
# QuickSaveAlias - macOS/Zsh Installation Script
# Usage: curl -fsSL https://raw.githubusercontent.com/YOUR_USER/QuickSaveAlias/main/install_mac.sh | zsh

set -e

echo "🚀 Installing QuickSaveAlias for macOS/Zsh..."
echo ""

# Detect if we're in the repo or need to download
if [[ -f "./quicksavealias_mac.sh" ]]; then
    echo "📁 Using local files from current directory"
    SCRIPT_DIR="$(pwd)"
    USE_LOCAL=1
else
    echo "📥 Downloading from GitHub..."
    USE_LOCAL=0
    
    # You can replace this with your actual GitHub URL
    GITHUB_RAW_URL="https://raw.githubusercontent.com/loganathan001/QuickSaveAlias/main"
    
    # Create temp directory
    TMP_DIR=$(mktemp -d)
    cd "$TMP_DIR"
    
    # Download required files
    echo "   Downloading quicksavealias_mac.sh..."
    curl -fsSL "${GITHUB_RAW_URL}/quicksavealias_mac.sh" -o quicksavealias_mac.sh || {
        echo "❌ Failed to download quicksavealias_mac.sh"
        echo "   Please check the GitHub URL or clone the repository manually."
        exit 1
    }
    
    echo "   Downloading zsh_special_aliases.sh..."
    curl -fsSL "${GITHUB_RAW_URL}/zsh_special_aliases.sh" -o zsh_special_aliases.sh || {
        echo "❌ Failed to download zsh_special_aliases.sh"
        exit 1
    }
    
    SCRIPT_DIR="$TMP_DIR"
fi

echo ""
echo "📦 Installing files..."

# Backup existing files if they exist
if [[ -f ~/.quicksavealias.sh ]]; then
    cp ~/.quicksavealias.sh ~/.quicksavealias.sh.backup-$(date +%Y%m%d-%H%M%S)
    echo "   ✓ Backed up existing ~/.quicksavealias.sh"
fi

if [[ -f ~/.zsh_special_aliases.sh ]]; then
    cp ~/.zsh_special_aliases.sh ~/.zsh_special_aliases.sh.backup-$(date +%Y%m%d-%H%M%S)
    echo "   ✓ Backed up existing ~/.zsh_special_aliases.sh"
fi

# Install the scripts
cp "${SCRIPT_DIR}/quicksavealias_mac.sh" ~/.quicksavealias.sh
cp "${SCRIPT_DIR}/zsh_special_aliases.sh" ~/.zsh_special_aliases.sh
chmod +x ~/.quicksavealias.sh ~/.zsh_special_aliases.sh

echo "   ✓ Installed ~/.quicksavealias.sh"
echo "   ✓ Installed ~/.zsh_special_aliases.sh"

echo ""
echo "⚙️  Configuring ~/.zshrc..."

# Check if already configured
if grep -q "quicksavealias.sh" ~/.zshrc 2>/dev/null && grep -q "zsh_special_aliases.sh" ~/.zshrc 2>/dev/null; then
    echo "   ✓ Already configured in ~/.zshrc"
else
    # Add to .zshrc
    echo '' >> ~/.zshrc
    echo '# QuickSaveAlias - Persistent alias management' >> ~/.zshrc
    echo '[ -e ~/.quicksavealias.sh ] && source ~/.quicksavealias.sh -install' >> ~/.zshrc
    echo '[ -f ~/.zsh_special_aliases.sh ] && source ~/.zsh_special_aliases.sh' >> ~/.zshrc
    echo "   ✓ Added QuickSaveAlias to ~/.zshrc"
fi

# Initialize the aliases file if it doesn't exist
if [[ ! -f ~/.zsh-aliases ]]; then
    echo "# Zsh aliases file - auto-generated by QuickSaveAlias" > ~/.zsh-aliases
    echo "# Special character aliases are managed in ~/.zsh_special_aliases.sh" >> ~/.zsh-aliases
    echo "   ✓ Created ~/.zsh-aliases"
fi

# Clean up temp directory if we downloaded files
if [[ $USE_LOCAL -eq 0 ]]; then
    cd ~
    rm -rf "$TMP_DIR"
fi

echo ""
echo "✅ Installation complete!"
echo ""
echo "📝 Next steps:"
echo "   1. Close and reopen your terminal (or run: source ~/.zshrc)"
echo "   2. Test with: alh (shows help)"
echo "   3. Create your first alias: adal test 'echo Hello!'"
echo ""
echo "📚 Documentation:"
echo "   - README: https://github.com/loganathan001/QuickSaveAlias"
echo "   - Run 'alh' for usage guide"
echo ""
echo "🎉 Enjoy QuickSaveAlias!"
